export const VALUES = [
  "('Blackhat', 'Action|Crime|Drama|Mystery|Thriller')",
  "('Devils, The', 'Drama')",
  "('Marvellous', 'Drama')",
  "('Munyurangabo', 'Drama')",
  "('George Washington Slept Here', 'Comedy')",
  "('Zero Theorem, The', 'Drama|Fantasy|Sci-Fi')",
  "('The Sinners of Hell', 'Drama|Horror')",
  "('Raise the Red Lantern (Da hong deng long gao gao gua)', 'Drama')",
  "('Super Inframan, The (Zhong guo chao ren)', 'Action|Fantasy|Sci-Fi')",
  "('Incendies', 'Drama|Mystery|War')",
  "('Judith of Bethulia', 'Adventure|Drama|Romance')",
  "('Roman Spring of Mrs. Stone, The', 'Drama|Romance')",
  "('Lizzie McGuire Movie, The', 'Children|Comedy|Romance')",
  "('Lovely & Amazing', 'Comedy|Drama|Romance')",
  "('Who Is Killing the Great Chefs of Europe?', 'Comedy|Crime|Mystery')",
  "('Lucky 7', 'Comedy|Romance')",
  "('Glue', 'Drama')",
  "('Nelly & Monsieur Arnaud', 'Drama')",
  "('Young People', 'Drama')",
  "('Grandmaster, The (Yi dai zong shi)', 'Action|Drama|IMAX')",
  "('Lumiere and Company (Lumière et compagnie)', 'Documentary')",
  "('Transcendence', 'Drama|Sci-Fi|IMAX')",
  "('Killjoy', 'Horror')",
  "('Ax, The (couperet, Le)', 'Comedy|Crime')",
  "('Just Around the Corner', 'Comedy|Musical')",
  "('Buck and the Preacher', 'Western')",
  "('Kummeli V', 'Comedy')",
  "('Scream 2', 'Comedy|Horror|Mystery|Thriller')",
  "('Dry White Season, A', 'Drama|Thriller')",
  "('Swan, The', 'Comedy|Drama|Romance')",
  "('Unloved, The', 'Drama')",
  "('Blues Harp', 'Crime|Drama')",
  "('Punks', 'Comedy')",
  "('Soldier''s Girl', 'Drama')",
  "('Lascars', 'Animation|Comedy')",
  "('Looking for Hortense (Cherchez Hortense) ', 'Drama')",
  "('Wszystko, co kocham', 'Comedy|Drama')",
  "('Angele', 'Drama')",
  "('Firewalker', 'Adventure')",
  "('12 Dates of Christmas', 'Children|Comedy|Fantasy|Romance')",
  "('World Apart, A', 'Drama')",
  "('Bullfighter and the Lady', 'Action|Drama|Romance')",
  "('Two Bits', 'Drama')",
  "('Walk in the Sun, A', 'War')",
  "('Gertie the Dinosaur', 'Animation|Children|Comedy')",
  "('Emperor of the North (Emperor of the North Pole)', 'Action|Drama|Thriller')",
  "('Murder in Coweta County', 'Crime|Drama')",
  "('Finding Neverland', 'Drama')",
  "('Our Daily Bread (Unser täglich Brot)', 'Documentary')",
  "('Once Upon a Time in China (Wong Fei Hung)', 'Action|Adventure|Drama')",
  "('Autumn in New York', 'Drama|Romance')",
  "('Earthling, The', 'Adventure|Drama')",
  "('K-11', 'Crime|Drama')",
  "('Plutonium Circus', 'Documentary')",
  "('Werner - Gekotzt wird später', 'Animation|Comedy')",
  "('Dark Woods (Villmark)', 'Adventure|Horror|Mystery|Thriller')",
  "('Here Comes the Devil (Ahí va el diablo)', 'Horror|Thriller')",
  "('Other, The', 'Drama|Horror|Mystery')",
  "('My Louisiana Sky', 'Drama')",
  "('Home of Our Own, A', 'Drama')",
  "('Network', 'Comedy|Drama')",
  "('Breakfast on Pluto', 'Comedy|Drama')",
  "('A.I. Artificial Intelligence', 'Adventure|Drama|Sci-Fi')",
  "('Palindromes', 'Adventure|Comedy|Drama')",
  "('Out of Towners, The', 'Comedy')",
  "('Saving Otter 501', 'Documentary')",
  "('Without Pity', 'Crime|Drama')",
  "('Sentimental Swordsman, The', 'Action|Adventure')",
  "('We and the I, The', 'Drama')",
  "('Crimes of the Heart', 'Comedy|Drama')",
  "('Earth (Zemlya)', 'Drama')",
  "('Garage Olimpo', 'Drama')",
  "('Mumblecore', 'Drama|Romance')",
  "('Hum Aapke Hain Koun...!', 'Comedy|Drama|Musical')",
  "('Blossoms in the Dust', 'Drama')",
  "('Book of Love', 'Comedy|Romance')",
  "('Roseland', 'Drama|Musical|Romance')",
  "('Messenger, The', 'Drama|Romance|War')",
  "('Glimmer Man, The', 'Action|Thriller')",
  "('Love the Beast', 'Documentary')",
  "('Lake of Fire', 'Documentary')",
  "('In a Town This Size', 'Documentary')",
  "('Fantastic Four', 'Action|Adventure|Sci-Fi')",
  "('Moine, Le (Monk, The)', 'Drama|Mystery|Thriller')",
  "('Saints and Soldiers', 'Action|Adventure|Drama|War')",
  "('Camille Claudel', 'Drama')",
  "('Salvador (Puig Antich)', 'Drama')",
  "('Track 29', 'Drama|Mystery')",
  "('Anything Goes', 'Musical')",
  "('Wicker Park', 'Drama|Romance|Thriller')",
  "('Lucy', 'Comedy|Drama')",
  "('Male and Female', 'Adventure|Drama')",
  "('Resurrecting the Champ', 'Drama')",
  "('In the Midst of Life (Au coeur de la vie)', 'Drama|War')",
  "('Beyond the Black Rainbow', 'Mystery|Sci-Fi')",
  "('Hamlet Goes Business (Hamlet liikemaailmassa)', 'Comedy|Drama|Romance')",
  "('Food Matters', 'Documentary')",
  "('Princess (Prinsessa)', 'Drama')",
  "('Third Wheel, The', 'Comedy|Romance')",
  "('Thief', 'Crime|Drama|Thriller')"
];

export const SCHEMA = `(
  id integer PRIMARY KEY UNIQUE,
  title TEXT,
  genre TEXT
)`;